### PR TITLE
Synchronize scripts to randomizer v2

### PR DESCRIPTION
**Pull request by kburger**
Some minor other changes. I've pointed the output folders to the same folder as the randomizer script is pointing to. What do you think: should we make separate sub-folders for the output, or can we write all files to that folder without any hierarchy?

### CODE REVIEW

**Review by NuriaQueralt — COMMENTED** [review]
reminder for me: check the output path in readme

**Review by NuriaQueralt — COMMENTED** [review]
Reminder for myself: add PGE2 binary values column

**Comment by NuriaQueralt** [comment]
> Some minor other changes. I've pointed the output folders to the same folder as the randomizer script is pointing to. What do you think: should we make separate sub-folders for the output, or can we write all files to that folder without any hierarchy?

Good question! I don't expect a lot of versions for this type of generation of synthetic data since I hope to have access to real data at some point, so for now, I would keep it simple and write all files in the same out/ folder, where I would keep the naming scheme, exp1_, exp2 ... and just distinguish them by format extension CSV or TTL. If we tend to have more and more versions then we can recapitulate. What do you think? Apart from that, from my side go ahead with the merge :)

**Comment by kburger** [comment]
> > Some minor other changes. I've pointed the output folders to the same folder as the randomizer script is pointing to. What do you think: should we make separate sub-folders for the output, or can we write all files to that folder without any hierarchy?
> 
> Good question! I don't expect a lot of versions for this type of generation of synthetic data since I hope to have access to real data at some point, so for now, I would keep it simple and write all files in the same out/ folder, where I would keep the naming scheme, exp1_, exp2 ... and just distinguish them by format extension CSV or TTL. If we tend to have more and more versions then we can recapitulate. What do you think? Apart from that, from my side go ahead with the merge :)

Agreed. I'll merge, thanks for the feedback.

**Pull request merged**
